version:0.2
phases:
	pre_build:
		commands:
			- echo "Entered the pre_build stage"
	build:
		commands:
			- echo "Entered the build stage"
			- mvn clean prepare-package war:exploded
	post_build:
		commands:
			- echo "Entered the post_build stage"
			- mv target/deploy ./
artifacts:
	files:
		- deploy/**/*